organ-printer/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :user_organs, only: [:index, :new, :create]
  end
  resources :user_organs, only: [:show, :destroy]


  ## CUSTOM ROUTE FOR STORING A USER-ORGAN ##
  ## PUT or PATCH? ##
  put '/store', to:'users#store'
  put "/user_organs/:id/check", to:'user_organs#check'
  
  ## REGISTER ##
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  ## LOGIN ##
  get "/login", to: 'login#new'
  post "/login", to: 'login#create'
  delete '/logout', to: 'login#destroy'

end

organ-printer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

organ-printer/app/models/component.rb
class Component < ApplicationRecord
  has_many :requirements, dependent: :destroy
end

organ-printer/app/models/organ.rb
class Organ < ApplicationRecord
  has_many :requirements, dependent: :destroy
  has_many :user_organs, dependent: :destroy
  has_many :components, through: :requirements

  def cost_to_build
    self.components.map {|component| component.price}.sum
  end

  def random_price
    #want it to be between 20% and 400% of the cost o build
    self.cost_to_build * rand(0.1..4.0).round(2)
  end

end

organ-printer/app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :organ
  belongs_to :component

end

organ-printer/app/models/user.rb
class User < ApplicationRecord
  
  has_many :user_organs, dependent: :destroy
  has_many :organs, through: :user_organs
  validates :username, presence: true, uniqueness: true
  has_secure_password
  
end

organ-printer/app/models/user_organ.rb
class UserOrgan < ApplicationRecord
  belongs_to :user
  belongs_to :organ
  # has_many :components, through: :organ

  def check_minimum(checked_ids)
    min = self.organ.minimum_component_count
    if checked_ids.count < min
      return "You must select at least #{min} components"
    else
      return nil
    end
  end

  def compare_ids(checked_ids)
    required_ids = self.organ.components.map {|component| component.id}
    required_ids.each do |id|
      if !checked_ids.try(:include?, id.to_s)
        return Component.find(id).missing_error
      end
    end
    return nil
  end

end

organ-printer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_up_auth_variables
  before_action :authorized

  def set_up_auth_variables
    @user_id = session["user_id"]
    @logged_in = !!@user_id
    if @logged_in
      @current_user = User.find_by(id: @user_id)
      if !@current_user
        session.clear
      end
    end
  end

  def authorized
    #unless is like if !(condition)
    unless @logged_in
      flash[:message] = "Please login to view this page"
      return redirect_to login_path
    end

    if @current_user.balance < 0
      flash[:warning] = "The black-market mafia is hot on your trail ... get out of debt ASAP or risk being shot "
    else
      flash[:warning] = nil
    end
  end

  def logout
    session["user_id"] = nil
  end

end

organ-printer/app/controllers/components_controller.rb
class ComponentsController < ApplicationController
end

organ-printer/app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    if @logged_in
      redirect_to @current_user
    else
      render 'new'
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session["user_id"] = @user.id
      redirect_to @user
    else
      flash[:message] = "Incorrect username or password"
      #byebug
      redirect_to '/login'
    end
  end

  def destroy
    logout
    redirect_to '/login'
  end

end

organ-printer/app/controllers/organs_controller.rb
class OrgansController < ApplicationController
end

organ-printer/app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
end

organ-printer/app/controllers/user_organs_controller.rb
class UserOrgansController < ApplicationController

  def index
    @user_organs = @current_user.user_organs
  end

  def new
      @user_organ = UserOrgan.new(flash[:user_org_hash])
      @organs = Organ.all
      @components = Component.all
      @selected_components = flash[:array] || []
  end

  def create

    @user_organ = UserOrgan.new(params.require(:user_organ).permit(:organ_id))
    @user_organ.user_id = @user_id
    @selected_components = params[:components]
    flash[:array] = @selected_components
    flash[:user_org_hash] = @user_organ.attributes

    if @user_organ.compare_ids(@selected_components) != nil
      flash[:error] = @user_organ.compare_ids(@selected_components)
    elsif @user_organ.check_minimum(@selected_components)
      flash[:error] = @user_organ.check_minimum(@selected_components)
    end

    if flash[:error]
      @organs = Organ.all
      @components = Component.all
      redirect_to new_user_user_organ_path
    else
      @user_organ.save
      @new_balance = @user_organ.user.balance - @selected_components.map{|t| Component.find(t).price}.sum
      @user_organ.user.update(balance: @new_balance)
      redirect_to @user_organ
    end
  end

  def show
    flash[:cant_leave] = "freeze page"
    @user_organ = UserOrgan.find(params[:id])
    @price = @user_organ.organ.random_price.round(2)
  end

  def check
    @user_organ = UserOrgan.find(params[:id])
    @balance = @current_user.balance - 100.0
    @current_user.update(balance: @balance)
    redirect_to @user_organ
  end

  def destroy
    @price = params[:price].to_f
    @new_balance = @current_user.balance + @price
    @current_user.update(balance: @new_balance)
    @user_organ = UserOrgan.find(params[:id])
    @user_organ.destroy
    redirect_to @current_user
  end

end

organ-printer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def show
    if @logged_in
    else
      redirect_to '/login'
    end
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.update(balance: 500.00)
      session["user_id"] = @user.id
      flash[:message] = "Registered #{@user.username}"
      redirect_to @user
    else
      flash[:message] = "Inapropriate Registration Info"
      redirect_to new_user_path
    end
  end

  def edit
    render 'edit'
  end

  def update
    @current_user.update(user_params)
    redirect_to @current_user
  end

  def store
    @balance = @current_user.balance - 100.0
    @current_user.update(balance: @balance)
    redirect_to user_user_organs_path(@current_user)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

organ-printer/app/helpers/application_helper.rb
module ApplicationHelper
end

organ-printer/app/helpers/components_helper.rb
module ComponentsHelper
end

organ-printer/app/helpers/login_helper.rb
module LoginHelper
end

organ-printer/app/helpers/organs_helper.rb
module OrgansHelper
end

organ-printer/app/helpers/requirements_helper.rb
module RequirementsHelper
end

organ-printer/app/helpers/user_organs_helper.rb
module UserOrgansHelper
end

organ-printer/app/helpers/users_helper.rb
module UsersHelper
end

organ-printer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrganPrinter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>

      <% if flash[:cant_leave] %>
        <nav class="navbar">

          <h4 class="nav_bar_element">OrganPrinter(TM)</h4>
          <h4 class="nav_bar_element">Logged in as <%= @current_user.username %></h4>
          <h4 class="nav_bar_element">Remaining Balance: $<%= @current_user.balance %></h4>

        </nav>
      <% else %>
      
        <nav class="navbar">

          <h4 class="nav_bar_element">OrganPrinter(TM)</h4>
            <% if @logged_in %>
              <h4 class="nav_bar_element">Logged in as <%= @current_user.username %></h4>
              <h4 class="nav_bar_element">Remaining Balance: $<%= @current_user.balance %></h4>
              <%= button_to 'Home', @current_user, method: :get, class:"btn, btn-success" %>
              <%= button_to 'Edit Account', edit_user_path(@current_user), method: :get, class:"btn, btn-success" %>
              <%= button_to "Logout", "/logout", method: :delete, class:"btn, btn-success" %>

            <% else %>
              <%= button_to "Login", "/login", method: :get, class:"btn, btn-success" %>
              <%= button_to "Register", new_user_path, method: :get, class:"btn, btn-success" %>
            <% end %>

        </nav>
      
      <% end %>

      <% if !!flash[:message] %>
        <h5 style="color: orangered;" class="text-center">========= |<%= flash[:message] %>| =========</h5>
      <% end %>

      <% if !!flash[:warning] %>
          <font color="YELLOW">
            <marquee BGCOLOR="RED" scrollamount="15" behavior="alternate" style="padding-top:15px;padding-bottom:15px;">
            <i>========= |<%= flash[:warning] %>| =========</i>
            </marquee>
        </font>
      <% end %>

    </header>
      <div class="yield container center-text">

        <%= yield %>

      </div>
  </body>
</html>

organ-printer/app/views/login/new.erb
<!-- LOGIN NEW PAGE -->

<h4 id="login_title" class="container text-center">Input Credentials</h4>

<div class="container text-center">
  <%= form_tag '/login' do %>
    <p><%= label_tag :username %></p>
    <%= text_field_tag :username %>

    <p><%= label_tag :password %></p>
    <%= password_field_tag :password %>
    <br><br>
    <%= submit_tag "Login", class:"btn, btn-success" %>
  <% end %>
</div>

organ-printer/app/views/user_organs/index.erb
<h1><%= "Hi, #{@current_user.username}" %></h1>
<h2><%= "Your organ stock includes: " %></h2>
<ol>
<% @user_organs.each do |user_organ| %>
  <li>
  <h3><%= user_organ.organ.name %></h3><br>
    <%= button_to "Check Current Market Price (Cost to check: $100, fibe-optic warp speed transmission overhead)",
    "/user_organs/#{user_organ.id}/check",
    method: :put%>
  </li>
<% end %>
</ol>

organ-printer/app/views/user_organs/new.erb
<h1 style="margin-left: 15px;">Organ Printer</h1>

<% if flash[:error] != nil %>
    <font color="RED">
      <marquee BGCOLOR=YELLOW scrollamount="20">
        <i>========= |<%= flash[:error] %>| =========</i>
      </marquee>
    </font>
<% end %>


<h3 style="margin-left: 15px;">Print a new organ by selecting the correct combination of components</h3>

<%= form_for @user_organ, url: {action: "create"} do |f| %>
  <span class="container center-text" style="font-size: 20pt;">
    <%= f.label :organ_id %>
    <%= f.collection_select :organ_id, @organs, :id, :name %>
  </span>

<div class="container-main container-fluid">

  <div class="row">
    <h4 class="container center-text"><%= f.label "Components:" %></h4>
  </div>

  <div class="row">
    <div class="col-xs-1">
      <% @components.each do |component| %>
        <%= label_tag "| #{component.name} - $#{component.price} ->" %>
        <%= check_box_tag "components[]", component.id, @selected_components.include?(component.id.to_s) %>
      <% end %>
    </div>
  </div>

  <div class="container center-text">
    <%= f.submit class:"btn btn-success" %>
  </div>
    <% end %>

</div>

organ-printer/app/views/user_organs/show.erb
<!-- <div class="container center-text"> -->

  <h1>Current Selling Price of This <%= @user_organ.organ.name %></h1>
  <h2> $<%= @price %></h2>

  <% if @user_organ.organ.try(:image) %>
    <%= image_tag @user_organ.organ.image, style:"height:400px;width:500px;" %>
  <% end %>

  <%= form_tag user_organ_path(@user_organ), method: :delete do %>
    <%= hidden_field_tag :price, @price %><br>
    <%= submit_tag "Sell" %><br>
  <% end %>
  <br>
  <%= button_to "Store for $100", '/store', method: :put %>

<!-- </div> -->

organ-printer/app/views/users/edit.erb
<div class="user_edit_form container text-center">
  <h4 style="padding-bottom: 10px;color: lightgreen;">Edit Account Details:</h4>

  <%= form_for @current_user do |f| %>
    <h5 style="color: lightgreen;">Username: </h5><%= f.text_field :username, :value => "" %>
    <br><br>

    <h5 style="color: lightgreen;">Password: </h5><%= f.password_field :password_digest %>
    <br><br>

    <%= f.submit "Update Account", class:"btn, btn-success" %>
  <% end %>

</div>

organ-printer/app/views/users/new.erb
<!-- USER NEW PAGE -->

<h1 class="container text-center">Registration</h1>

<div class="container text-center">
  <%= form_for @user do |f| %>
    <p><%= f.label :username %></p>
    <%= f.text_field :username %>

    <p><%= f.label :password %></p>
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit "Register" %>
  <% end %>
</div>

organ-printer/app/views/users/organs.html.erb
<% if @organs %>

  <%= "#{@user.username}, your organs are: " %>
    <ul>
    <% @organs.each do |organ| %>
      <li><%= organ.name %></li>
      <% end %>
    </ul>

<% else %>

  <%= "#{@user.username}, you don't have any organs yet." %>

<% end %>

organ-printer/app/views/users/show.html.erb
<h4 class="container text-center">What would you like to do today?</h4>

<nav class="navbar ">
    <%= button_to "Build an Organ", "/users/#{@user_id}/user_organs/new", method: :get, class:"btn, btn-success" %>

    <%= button_to "View Stock", "/users/#{@user_id}/user_organs", method: :get, class:"btn, btn-success" %>
</nav>